### ISSUE TITLE
Create UML Diagrams

### ISSUE THREAD

**Issue by hd2802** [hd2802/Dungeon-Delver#35]
Only 2 are required for the report but these are valuable things to have so if we need more than 2 that is fine

**Comment by ArtiomC15** [comment]
![Image](https://github.com/hd2802/ESP/assets/124717171/80dcb934-6309-4490-88e2-897306d99252)
![Image](https://github.com/hd2802/ESP/assets/124717171/b570628d-7e71-4a8a-919e-e1b5939ab7a7)

**Comment by ArtiomC15** [comment]
New User have a unique identifier (user_id) and can register using the register() method.
Registered User inherits from New User and includes additional attributes such as username, password, and email.
Registered User has operations for authentication (login() and logout()) and choosing an account type (chooseAccountType()).

There are two subclasses of Registered User: Player and DM (Dungeon Master).
Both Player and DM inherit from Registered User and have specific methods related to their roles in the D&D environment.

Player has methods for viewing tutorials, content, and characters, searching for content, creating and editing characters, and joining campaigns.

DM has methods for viewing tutorials, content, and campaigns, searching for content, creating and editing campaigns.
Content:

Content Class:
Represents general content in the system with attributes such as contentID, title, and description.
Methods are displayContent() and updateContent().

Tutorial Class:
Represents tutorials, a specific type of content, with additional attributes (tutorialID, tutorialName).
Methods are displayTutorial(), saveProgress(), and closeTutorial().
Tutorial inherits from Content,.

Content class retrieves data from the database

**Comment by hd2802** [comment]
I know that you have a lot of tasks to do at the moment, but would it be possible to turn these bullet points into a paragraph to accompany the diagrams?
