### ISSUE TITLE
Create Design Prototype

### ISSUE THREAD

**Issue by hd2802** [hd2802/Dungeon-Delver#37]
Use https://www.figma.com/

Create a basic design prototype for how the website should look.

This would include the general scheme of the website but also can include how specific pages should be displayed.

BASICALLY GOING TO CHANGE ALL OF THIS

**Comment by hd2802** [comment]
![Image](https://github.com/hd2802/ESP/assets/146767175/48d06625-f508-4c93-8c6a-0ebd89236eb5)

**Comment by hd2802** [comment]
Light mode general page display

![Image](https://github.com/hd2802/ESP/assets/146767175/dff9da78-cb09-493a-9a6f-a92bdc974fb1)

**Comment by hd2802** [comment]
Example of how the character sheet creation could work:


![Image](https://github.com/hd2802/ESP/assets/146767175/4dc663a1-c9f1-41c8-b0fa-cb77da29d7a2)

**Comment by MatthewHarris123** [comment]
If the image from which the inspiration is taken from is being used, should we reference where we found it? if so, should that be included in the image or will we just write that under the image?

**Comment by hd2802** [comment]
![Image](https://github.com/hd2802/ESP/assets/146767175/806b0f01-7092-4764-a4fd-4fa032a6a282)
