### ISSUE TITLE
Report: Translation of requirements to interactions/features (needs 'interaction with stakeholders')

### ISSUE THREAD

**Issue by hd2802** [hd2802/Dungeon-Delver#55]
As the title says, this part of the report gives a -4% penalty if we do not mention what the stakeholders want in a D&D website.

So something along the lines of 'stakeholders mentioned that .... so for the website it was decided that .... would be an implementation of requirement ....'

This section also NEEDS to explicitly mention the requirements by their number (from the requirements table)

If this section becomes a bit repetitive (i.e. to implement requirement x we did ...) this may look good in a table

| Requirement | Planned implementation |
| ------------ | ------------------------ | 
| 2.3                | Log in feature (more explanation though) |

**Comment by ArtiomC15** [comment]
Tried to do it a bit more general, idk how well that works

User Registration (2.1):
This feature for a straightforward account creation process and the inclusion of sub-features like saving key information were group decisions based on the desire to enhance user engagement.
Interactive Rulebook (2.2):
Stakeholders strongly influenced the development of the interactive rulebook. Their input suggested the need for a comprehensive system with examples, complementary information, and a reduced set of rules for new accounts for better understanding.
Character Creation Function (2.3):
Stakeholders played a significant role in shaping the character creation function. Their input led to the development of a step-by-step process, 'new player mode,' and a diverse range of character options to cater to different player preferences.
Character Management (2.4):
Group decisions drove the features related to character management, including the ability to make changes post-creation, manage multiple characters within a single account, and the 'star' function for prioritized character sheets.
New Player Mode (2.5):
Stakeholders strongly advocated for a new player mode with an interactive tutorial campaign and pop-up text guidance to ease newcomers into the world of D&D.
DM Tools (2.6):
Stakeholders, particularly Dungeon Masters, influenced the development of DM tools. Features like privately rolling dice, an automatically sorted initiative table, and a monster compendium with quick searching and 'starring' were included based on their specific needs.
Social Network (2.7) and Group Function (2.8):
Stakeholders emphasized the communal aspect of D&D, leading to the inclusion of social network features ('friending' other accounts) and group functions with assigned roles and communication features.
Performance (3.1) and Reliability (3.2):
These requirements were decided by the group, aiming to ensure a responsive and reliable platform without specific input from stakeholders.
Security (3.3) and Compatibility (3.4):
Security measures and compatibility requirements were group decisions, focusing on ensuring a secure environment and consistent performance across different browsers, devices, and operating systems.
Usability (3.5):
Usability considerations, including an accessible and user-friendly interface, were determined by the group to create a platform catering to a diverse audience.
