### ISSUE TITLE
Report: Conflict management between requirements

### ISSUE THREAD

**Issue by hd2802** [hd2802/Dungeon-Delver#57]

**Comment by ArtiomC15** [comment]
The balance of performance with usability ensures that interacting with the Web site is fluid and appealing. Performance optimisation makes for quick loading times as well as responsive interaction and usability ensures that an individual finds the layout intuitive and easy to use. That being said, these measures for improving performance like graphic reduction and compression of data may be counterproductive resulting in damaged visual appearance and utility. Therefore, complex design decisions are required so as to create a website that loads in three seconds and updates the data entered by a user at the same time.

Interaction of reliability and security is another issue. A robust infrastructure and continuous monitoring ensure availability of more than 99 per cent (3.2.1). Though it is highly secure with strict logs for logging in and user data (3.3), many complex issues affect the trustworthiness of the system. Therefore, a balance has to be achieved between ensuring that individuals keep benefiting from using the system and safeguarding confidential information from unapproved use. Encryption, authentication and intrusion detection protocols should be adopted but it should also not compromise the service and user experience.

For this reason, the solution entails good planning, thorough testing of prototypes and flexible designing methods. However, such a principle involves the mutual influence of performance- and availability-related issues with the reliability and safety procedures. Agile development process and regular updates are necessary for reconciling conflicting requirements, solving arising problems and meeting user expectations that constantly change. Ultimately, the success of digital platforms boils down to mastering these complex trade-offs to produce superior products that are differentiable based on their performance and usability, reliability and security aspects of digital service provision.
